<div class="col-md-12 ">
    <p>Dem Patienten sind zurzeit folgende Sprüche zugeordnet:</p>

    <div>
        <table border="1" id="patient_has_maxims">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Text</th>
                    <th>Entfernen</th>
                </tr>
            </thead>
            
            <?php foreach ($this->maximsFromPatient as $key => $val): ?>
                <tr maximid="<?php echo $val->getId(); ?>">
                    <td>
                        <?php
                        echo $val->getId();
                        ?>
                    </td>
                    <td>
                        <?php
                        echo $val->getText();
                        ?>
                    </td>
                    <td>
                       <button name="btnRemove" type="button" class="btn btn-warning"><span class="glyphicon glyphicon-minus"></span></button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    
    <p>
        <br/>
        <button id="btnSubmit" type="button" class="btn btn-primary">Daten Übernehmen</button>
    </p>

    <table id="patient_maxim_table" border="">
        <thead>
            <tr>
                <th>ID</th>
                <th>Text</th>
                <th>Hinzufuegen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->maxims as $key => $val): ?>
                <tr>
                    <td>
                        <?php echo $val->getId(); ?>
                    </td>
                    <td>
                        <?php echo $val->getText(); ?>
                    </td>
                    <td>
                    </td>
                </tr>    
            <?php endforeach; ?>
        </tbody>
    </table>

</div>