<div class="container" >
    <div class="row">

        <div class="col-md-12 ">
            <h2>Dem Patienten sind zurzeit folgende Ablenkungsmöglikeiten zugeordnet:</h2>
            <p>
                <button id="btnSubmit" type="button" class="btn btn-primary">Daten Übernehmen</button>
            </p>
            <div>
                <table id="patient_has_distractions">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Text</th>
                            <th>Emotion</th>
                            <th>Entfernen</th>
                        </tr>
                    </thead>

                    <?php foreach ($this->distractionsFromPatient as $key => $val): ?>
                        <tr>
                            <td>
                                <?php
                                echo $val->getId();
                                ?>
                            </td>
                            <td>
                                <?php
                                echo $val->getText();
                                ?>
                            </td>
                            <td>
                                <?php
                                echo $val->getEmotionText();
                                ?>
                            </td>
                            <td class="center_column">
                                <button distractionid="<?php echo $val->getId(); ?>" name="btnRemove" type="button" class="btn btn-warning"><span class="glyphicon glyphicon-minus"></span></button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>

            <br/>
            <br/>

            <table id="patient_distraction_table" border="">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Text</th>
                        <th>Emotion</th>
                        <th>Hinzufuegen</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->distractions as $key => $val): ?>
                        <tr>
                            <td>
                                <?php echo $val->getId(); ?>
                            </td>
                            <td>
                                <?php echo $val->getText(); ?>
                            </td>
                            <td>
                                <?php echo $val->getEmotionText(); ?>
                            </td>
                            <td class="center_column">
                            </td>
                        </tr>    
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>