<div class="container" >
    <div class="row">

        <div class="col-md-12 ">
            <h2>Dem Patienten sind zurzeit folgende Sprüche zugeordnet:</h2>

            <p>         
                <button id="btnSubmit" type="button" class="btn btn-primary">Daten Übernehmen</button>       
            </p>
            </br>

            <div>
                <table id="patient_has_maxims">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Text</th>
                            <th class="center_column">Entfernen</th>
                        </tr>
                    </thead>

                    <?php foreach ($this->maximsFromPatient as $key => $val): ?>
                        <tr>
                            <td>
                                <?php
                                echo $val->getId();
                                ?>
                            </td>
                            <td>
                                <?php
                                echo $val->getText();
                                ?>
                            </td>
                            <td class="center_column">
                                <button maximid="<?php echo $val->getId(); ?>" name="btnRemove" type="button" class="btn btn-warning"><span class="glyphicon glyphicon-minus"></span></button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>

            <br/><br/><br/><br/>

            <table id="patient_maxim_table" >
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Text</th>
                        <th>Hinzufuegen</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->maxims as $key => $val): ?>
                        <tr>
                            <td>
                                <?php echo $val->getId(); ?>
                            </td>
                            <td>
                                <?php echo $val->getText(); ?>
                            </td>
                            <td class="center_column">
                            </td>
                        </tr>    
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>