<div class="container-fluid" >
    <div class="row">

        <div class="col-md-10 col-md-offset-1">

            <h1>Patient bearbeiten</h1>
            
            <table id="patient_edit_table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Vorname</th>
                        <th>Nachname</th>
                        <th>Geburtsdatum</th>
                        <th>E-Mail</th>
                        <th>Status</th>
                        <th>Daten</th>
                        <th>Notfallkoffer</th>
                        <th>Sprüche</th>                
                        <th>Ablenkung</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            

        </div>
    </div>
</div>