<div class="col-md-12">
    <table id="patient_edit_table" border="2">
        <thead>
            <tr>
                <th>ID</th>
                <th>Vorname</th>
                <th>Nachname</th>
                <th>Geburtsdatum</th>
                <th>E-Mail</th>
                <th>Benutzername</th>
                <th>Daten</th>
                <th>Notfallkoffer</th>
                <th>Sprüche</th>                
                <th>Ablenkung</th>
            </tr>
        </thead>
        <tbody>
          
        </tbody>
    </table>
</div>