<div class="container" >
    <div class="row">

        <div class="col-md-12">
            <h1>Daten pflegen</h1>

            <p>
                Für den Patienten müssen folgende Daten gefplegt werden
            <ul>
                <li>Notfallkofer</li>
                <li>Ablenkungen</li>
                <li>Spr&uuml;che</li>
            </ul>

            Klicken Sie auf "weiter" um die Daten <b>jetzt</b> zu vervollst&auml;ndigen
            </p>

            <a href="<?php echo $this->emergencyLink ?>">Weiter</a>
            <a href="<?php echo $this->startseite ?>">Startseite</a>
<!--            <input type="button" value="Weiter"/>-->
           
        </div>
    </div>
</div>