<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Suchtprophylaxe</title>

        <?php
        $this->headLink()->appendStylesheet('/css/bootstrap.min.css');
        $this->headLink()->appendStylesheet('/css/spl.css');
        echo $this->headLink();
        
        ?>

        <?php echo $this->jQuery() ; ?>

        <?php
        $this->headScript()->appendFile('/js/bootstrap/bootstrap.min.js');
        $this->headScript()->appendFile('/js/jquery/js/jquery-ui-1.10.3.custom.min.js');
        $this->headScript()->appendFile('/js/Menu.js');
        $this->headScript()->appendFile('/concept/jquery.transit.min.js');
//        $this->headScript()->appendFile('/concept/custom.js');
//
        echo $this->headScript();
        ?>


    </head>
    <body>

<!--        <a class="leftarrow"></a>
        
         <a class="rightarrow"></a>-->
       
        <div id="ontop">
            <div class="container">
                <div class="formRow">
                    <div class="top-info-wrapper">
                        <div id="logo" class="col-md-6">
                             <h2>Suchtprohylaxe</h2>
                        </div>
                        <div class="col-md-6">
                            <!--<h2>Suchtprohylaxe</h2>-->
                        </div>

                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div id="nav-bar" class="wrapper">
            <div class="container">
                <div class="formRow">
                    <div class="">
                        <div class="navbar ">
                            <div class="navbar-inner">

                                <div class="nav-collapse">
                                    <?php
                                    $this->navigation()->menu()->setPartial('menu.phtml'); // RICHTIGE
                                    echo $this->navigation();
                                    ?> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->layout()->content ?>

        <div id="footer" class="navbar-fixed-bottom">
            <div class="container">     
                <div class="navbar">
                    <?php
                    echo $this->navigation()->menu()->renderMenu($this->footer, array('ulClass' => 'nav'));
                    ?>
                </div>
            </div>
        </div>
    </body>
</html>