<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Schnellstart Anwendung</title>

        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet('/css/login.css') ?>

 

    </head>
    <body>
        <div class="container">
            <div class="row">
                <?php echo $this->layout()->content ?>
            </div>
        </div>

    </body>
</html>