<div class="container" >
    <div class="row">

        <div class="col-md-12 ">
            <h1>Ablenkungen</h1>
            <div>
                <button id="distraction_create" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>Neue Ablenkungs-Möglichkeit</button><br><br>
            </div>

            <table id="distraction_table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Text</th>
                        <th>Emotion</th>
                        <th>Bearbeiten</th>
                        <th>Löschen</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>


            <div id="distraction_dialog_edit">
                <h3>Möglichkeit anlegen</h3>

                <div id="distraction_form_errors">

                </div>

                <?php
                echo $this->form;
                ?>

            </div>

            <div id="distraction_dialog_confirm">
                <h3>Möglichkeit löschen</h3>
                <p>
                    Wollen Sie diese Ablenkungs-Möglichkeit wirklich löschen?
                </p>
                <input type="hidden" id="id_delete"/>
            </div>
        </div>
    </div>
</div>